spring:
  http:
    encoding:
      charset: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/mangotv?serverTimezone=UTC&useSSL=false
    username: mangotvadmin
    password: mangotvpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  tomcat:
    uri-encoding: utf-8