spring:
  http:
    encoding:
      charset: utf-8

  datasource:
    url: jdbc:mysql://localhost:3306/mangotv?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: mangotvadmin
    password: mangotvpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  mail:
    host: smtp.gmail.com
    port: 587
    username: test.kani123@gmail.com
    password: testaccount123!!
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        mime:
          charset: utf-8
        transport:
          protocol: smtp

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
#    cache: false  prod에서는 true로 해야함
    order: 0

#  cache:
#    ehcache:
#      config: classpath:ehcache.xml
#
#  resources:
#    cache:
#      cachecontrol:
#        max-age: 5
#        no-store: false

jwt:
  secret-key: SecretKeyForJWTInEmailAuthenticationCode

server:
  tomcat:
    uri-encoding: utf-8